Repository Stormald/MangaFilRouge, pull requests merged in 2022-03, with the labels that each got.

#65 Get All List Status
  Back/Server/Controllers/CategoryListPersoController.cs
  Back/Server/Repositories/MariaDB/CategoryListPersoRepository.cs
  Back/Server/Services/CategoryListPersoService.cs
Labels: V1, Difficile, 4

#67 Schedule basic
  Front/src/app/components/schedule/schedule.component.html
  Front/src/app/components/schedule/schedule.component.ts
  Front/src/app/models/day.model.ts
Labels: 5

#70 Status LIST OK dans le form
  Front/src/app/components/modal-add-to-my-list/modal-add-to-my-list.component.html
  Front/src/app/components/modal-add-to-my-list/modal-add-to-my-list.component.ts
  Front/src/app/models/status.model.ts
  Front/src/app/services/status.service.spec.ts
  Front/src/app/services/status.service.ts
Labels: 4, Front
